hostels/urls.py
# -*- conding: utf-8 -*-
from django.conf.urls import url

from . import views


app_name = 'hostels'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),


    ###   Operator URLs   ###

    url(r'^beds/$', views.BedListView.as_view(), name='bed_list'),
    url(r'^bed/(?P<bed_id>\d+)/create_order$', views.CreateActualOrderView.as_view(), name='create_actual_order'),
    url(r'^bed/(?P<bed_id>\d+)/tax_value$', views.BedTaxValueView.as_view(), name='bed_tax_value'),
    url(r'^bed/(?P<bed_id>\d+)/change_end_date$', views.ChangeOrderEndDateView.as_view(), name='change_order_end_date'),
    url(r'^bed/(?P<bed_id>\d+)/reservation$', views.CreateReservationView.as_view(), name='create_reservation'),
    url(r'^bed/(?P<bed_id>\d+)/confirm_completion$', views.ConfirmCompletionView.as_view(), name='confirm_completion'),
    url(r'^bed/(?P<bed_id>\d+)/activate_reservation$', views.ActivateReservationView.as_view(), name='activate_reservation'),
    url(r'^bed/(?P<bed_id>\d+)/cancel_reservation$', views.CancelReservationView.as_view(), name='cancel_reservation'),

    url(r'^reservation_calendar$', views.ReservationCalendarView.as_view(), name='reservation_calendar'),
    url(r'^taxes$', views.TaxesView.as_view(), name='tax_list'),
    url(r'^orders$', views.OrderListView.as_view(), name='order_list'),
    url(r'^hostels$', views.HostelListView.as_view(), name='hostel_list'),

    url(r'^order/(?P<order_id>\d+)/remove_reservation$', views.RemoveReservationView.as_view(), name='remove_reservation'),
    url(r'^order/(?P<order_id>\d+)/change_dates$', views.ChangeReservationDatesView.as_view(), name='change_reservation_dates'),


    ###   Manager URLs   ###

    url(r'^manage/$', views.ManageIndexView.as_view(), name='manage_index'),
    url(r'^manage/hostels/$', views.ManageHostelsView.as_view(), name='manage_hostels'),
    url(r'^manage/hostels/report', views.ManageHostelsReportView.as_view(), name='manage_hostels_report'),
    url(r'^manage/beds/$', views.ManageBedsView.as_view(), name='manage_beds'),
    url(r'^manage/operators/$', views.ManageOperatorsView.as_view(), name='manage_operators'),
    url(r'^manage/orders/$', views.ManageOrdersView.as_view(), name='manage_orders'),
    url(r'^manage/orders/history$', views.ManageOrdersHistoryView.as_view(), name='manage_orders_history'),
    url(r'^manage/charges/$', views.ManageChargesView.as_view(), name='manage_charges'),
    url(r'^manage/charges/history$', views.ManageChargesHistoryView.as_view(), name='manage_charges_history'),
    url(r'^manage/taxes/$', views.ManageTaxesView.as_view(), name='manage_taxes'),
    url(r'^manage/taxes/history$', views.ManageTaxesHistoryView.as_view(), name='manage_taxes_history'),

    url(r'^manage/hostel/(?P<id>\d+)$', views.ManageEditHostelView.as_view(), name='manage_edit_hostel'),
    url(r'^manage/bed/(?P<id>\d+)$', views.ManageEditBedView.as_view(), name='manage_edit_bed'),
    url(r'^manage/operator/(?P<id>\d+)$', views.ManageEditOperatorView.as_view(), name='manage_edit_operator'),
    url(r'^manage/order/(?P<id>\d+)$', views.ManageEditOrderView.as_view(), name='manage_edit_order'),
    url(r'^manage/charge/(?P<id>\d+)$', views.ManageEditChargeView.as_view(), name='manage_edit_charge'),
    url(r'^manage/tax/(?P<id>\d+)$', views.ManageEditTaxView.as_view(), name='manage_edit_taxes'),
    url(r'^manage/taxgrade/(?P<id>\d+)$', views.ManageEditTaxGradeView.as_view(), name='manage_edit_tax_grades'),




    ###   Utility URLs   ###

    url(r'^util/cleanup_old_data$', views.UtilCleanupOldDataView.as_view(), name='util_cleanup_old_data'),
    url(r'^util/refresh_all_beds$', views.UtilRefreshAllBedsView.as_view(), name='util_update_all_beds'),

]

webapp/urls.py
# -*- conding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'', include('hostels.urls')),
    url(r'^admin/', admin.site.urls),
]

hostels/models.py
# -*- coding: utf-8 -*-
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied


class Hostel(models.Model):
    city = models.CharField(max_length=50, verbose_name='Город')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    tax = models.ForeignKey('Tax', on_delete=models.CASCADE, verbose_name='Тариф')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')

    def orders(self):
        result = []
        for bed in self.bed_set.all():
            result += bed.order_set.all()
        return result

    def charges(self):
        result = []
        for order in self.orders():
            result += order.charge_set.all()
        return result

    def beds_count(self):
        return self.bed_set.count()

    def free_beds_count(self):
        return len([bed for bed in self.bed_set.all() if bed.actual_order is None])

    def nonfree_beds_count(self):
        return self.bed_set.count() - self.free_beds_count()

    def today_value_income(self):
        today = datetime.now().date()
        return self.period_value_income(start_date=today, end_date=today)

    def today_value_outgo(self):
        today = datetime.now().date()
        return self.period_value_outgo(start_date=today, end_date=today)

    def period_value_income(self, start_date, end_date):
        result = 0.0
        for charge in self.charges():
            if charge.is_income and (start_date <= charge.date.date() <= end_date):
                result += charge.value
        return result

    def period_value_outgo(self, start_date, end_date):
        result = 0.0
        for charge in self.charges():
            if not charge.is_income and (start_date <= charge.date.date() <= end_date):
                result += charge.value
        return result

    def today_settlements(self):
        today = datetime.now().date()
        return self.period_settlements(start_date=today, end_date=today)

    def today_departures(self):
        today = datetime.now().date()
        return self.period_departures(start_date=today, end_date=today)

    def period_settlements(self, start_date, end_date):
        return len(list(filter(
            (lambda charge:
                start_date <= charge.date.date() <= end_date
                and charge.reason == Charge.ORDER_ACTIVATION
            ),
            self.charges()
        )))

    def period_departures(self, start_date, end_date):
        return len(list(filter(
            (lambda order:
                start_date <= order.end_date <= end_date
                and order.status == Order.COMPLETED
            ),
            self.orders()
        )))

    def __str__(self):
        return '%s, %s' % (self.city, self.address)

    class Meta:
        verbose_name = 'Хостел'
        verbose_name_plural = 'Хостелы'


class Operator(models.Model):
    user = models.OneToOneField(User, verbose_name='Пользователь')
    full_name = models.CharField(max_length=50, verbose_name='ФИО')
    identification = models.CharField(max_length=150, verbose_name='Паспортные данные')
    phone_number = models.CharField(max_length=50, verbose_name='Номер телефона')
    hostels = models.ManyToManyField(Hostel, blank=True, verbose_name='Хостелы')
    is_admin = models.BooleanField(default=False, verbose_name='Администратор')

    def __str__(self):
        return '%s' % (self.full_name)

    class Meta:
        verbose_name = 'Оператор'
        verbose_name_plural = 'Операторы'

    def get_bed_list(self):
        return Bed.objects.filter(hostel__in=self.hostels.all())

    def get_bed(self, bed_id):
        bed = get_object_or_404(Bed, pk=bed_id)
        if bed in self.get_bed_list():
            return bed
        else:
            raise PermissionDenied

    def get_order_list(self):
        orders = []
        for bed in self.get_bed_list():
            orders += bed.order_set.all()
        return orders

    def get_order(self, order_id):
        order = get_object_or_404(Order, pk=order_id)
        if order in self.get_order_list():
            return order
        else:
            raise PermissionDenied


class Bed(models.Model):
    hostel = models.ForeignKey(Hostel, on_delete=models.CASCADE, verbose_name='Хостел')
    tax = models.ForeignKey('Tax', on_delete=models.CASCADE, verbose_name='Тариф')
    actual_order = models.OneToOneField(
        'Order',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='actual_bed',
        verbose_name='Текущий заказ'
    )

    MALE = 0
    FEMALE = 1
    Gender = (
        (MALE  , 'Муж'),
        (FEMALE, 'Жен'),
    )
    gender = models.IntegerField(choices=Gender, verbose_name='Пол')

    def gender_text(self):
        return Bed.Gender[self.gender][1]

    def __str__(self):
        return 'Кровать #%d (%s)' % (self.id, self.hostel)

    class Meta:
        verbose_name = 'Кровать'
        verbose_name_plural = 'Кровати'

    def get_tax_value(self, days=None, start_date=None, end_date=None):
        if days is None:
            days = (end_date - start_date).days

        # Для неправильных периодов ставим минимальную цену.
        if days < 0:
            days = 1

        # Особенность формулы количества дней. Не должно дублироваться в других местах системы.
        # Если человек заехал на день, то считаем цену как один день, а не ноль дней. 
        if (start_date is not None and start_date == end_date) or (days == 0):
            days = 1

        for grade in self.tax.sorted_grades(reverse=True):
            if days >= grade.threshold_days:
                return days * grade.day_price
        else:
            return 0

    def has_orders_for_date(self, date):
        for order in self.order_set.all():
            if order.start_date <= date <= order.end_date:
                return True
        else:
            return False

    def get_order_for_date(self, date):
        for order in self.order_set.all():
            if order.start_date <= date <= order.end_date:
                return order
        else:
            return None


class Charge(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, verbose_name='Заказ')
    value = models.FloatField(default=0.0, verbose_name='Сумма')
    is_income = models.BooleanField(verbose_name='Доход')
    date = models.DateTimeField(verbose_name='Дата формирования')

    ORDER_ACTIVATION = 0
    END_DATE_CHANGE = 1
    Reason = (
        (ORDER_ACTIVATION, 'Заселение'),
        (END_DATE_CHANGE , 'Изменение сроков проживания'),
    )
    reason = models.IntegerField(choices=Reason, verbose_name='Причина')

    def reason_text(self):
        return Charge.Reason[self.reason][1]

    class Meta:
        verbose_name = 'Платёж'
        verbose_name_plural = 'Платежи'


class Order(models.Model):
    bed = models.ForeignKey(Bed, verbose_name='Кровать')
    start_date = models.DateField(verbose_name='Дата въезда')
    end_date = models.DateField(verbose_name='Дата выезда')
    value = models.FloatField(default=0.0, verbose_name='Сумма')
    guest_full_name = models.CharField(max_length=100, verbose_name='ФИО клиента')
    guest_identification = models.CharField(max_length=150, verbose_name='Паспортные данные клиента')
    guest_phone_number = models.CharField(max_length=50, verbose_name='Телефоны клиента')

    RESERVED = 1
    AWAITING_ACTIVATION = 2
    RESERVATION_CANCELLED = 3
    ACTIVE = 4
    AWAITING_COMPLETION = 5
    COMPLETED = 6
    Status = (
        (RESERVED             , 'Забронирован'               ),
        (AWAITING_ACTIVATION  , 'Ожидает подтверждения брони'),
        (RESERVATION_CANCELLED, 'Бронирование отменено'      ),
        (ACTIVE               , 'Активен'                    ),
        (AWAITING_COMPLETION  , 'Готов к завершению'         ),
        (COMPLETED            , 'Успешно завершён'           ),
    )
    status = models.IntegerField(choices=Status, verbose_name='Статус')

    def status_text(self):
        return Order.Status[self.status - 1][1]

    def hostel(self):
        return self.bed.hostel
    hostel.short_description = 'Хостел'

    def __str__(self):
        return 'Заказ #%d' % (self.id)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def check_dates(self):
        fail = False

        if self.start_date > self.end_date:
            fail = True

        for other in self.bed.order_set.all():
            if self == other:
                continue
            is_before = (self.start_date <= other.start_date and self.end_date <= other.start_date)
            is_after = (self.start_date >= other.end_date and self.end_date >= other.end_date)
            if not (is_before or is_after):
                fail = True
        
        return not fail


class Tax(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тариф'
        verbose_name_plural = 'Тарифы'

    def sorted_grades(self, reverse=False):
        return sorted(
            self.taxgrade_set.all(),
            key=(lambda grade: grade.threshold_days),
            reverse=reverse,
        )


class TaxGrade(models.Model):
    tax = models.ForeignKey(Tax, on_delete=models.CASCADE)
    threshold_days = models.IntegerField()
    day_price = models.FloatField()

    def __str__(self):
        return 'Порог %d дней, тариф %s' % (self.threshold_days, self.tax.name)

    class Meta:
        verbose_name = 'Порог тарифа'
        verbose_name_plural = 'Пороги тарифа'


class OrderHistory(models.Model):
    order_id = models.IntegerField(default=0)
    bed = models.ForeignKey(Bed, verbose_name='Кровать')
    start_date = models.DateField(verbose_name='Дата въезда')
    end_date = models.DateField(verbose_name='Дата выезда')

hostels/templates/hostels/activate_reservation.html
{% extends "hostels/base.html" %}

{% block title %}Подтвердить бронирование{% endblock %}

{% block content %}
{% include "hostels/base_form.html" with submit_text="Готово" cancel_button="Отмена" glyphs=True %}
{% endblock %}

hostels/templates/hostels/alert_template.html
<div class="alert alert-{{type}}">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    {{ message }}
</div>

hostels/templates/hostels/base_form.html
{% load crispy_forms_tags %}

{% if error %}
    {% include "hostels/alert_template.html" with type="danger" message=error %}
{% endif %}

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
        <form role="form" method="post" class="{{ form_class }}">

            {% csrf_token %}

            {{ form | crispy }}

            <button type="submit" class="btn btn-default">
            {% if glyphs %}<span class="glyphicon glyphicon-ok"></span>{% endif %}
            {{ submit_text }}
            </button>

            {% if cancel_button %}
                <!-- <a href="{% url 'hostels:index' %}" class="btn btn-default">{% if glyphs %}<span class="glyphicon glyphicon-remove"></span>{% endif %} Отмена</a> -->
                <a onclick="window.history.back();" class="btn btn-default">{% if glyphs %}<span class="glyphicon glyphicon-remove"></span>{% endif %} Отмена</a>
            {% endif %}

        </form>
    </div>
    <div class="col-md-4">
    </div>
</div>

hostels/templates/hostels/confirm_completion.html
{% extends "hostels/base.html" %}

{% block title %}Подтвердить выселение{% endblock %}

{% block content %}
{% include "hostels/base_form.html" with submit_text="Готово" cancel_button="Отмена" glyphs=True %}
{% endblock %}

hostels/templates/hostels/manage_charges.html
{% extends 'hostels/base.html' %}

{% block title %}Платежи{% endblock %}

{% block content %}

    {% if error %}
        {% include "hostels/alert_template.html" with type="danger" message=error %}
    {% endif %}

    {% if request.GET %}
        <button type="button" class="btn btn-default" onclick="window.location = '{{ request.GET.back }}';"><span class="glyphicon glyphicon-arrow-left"></span> Назад</button>
    {% endif %}

    <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#createObject"><span class="glyphicon glyphicon-plus"></span> Добавить</button>

    <br><br>
    {% if charges %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Заказ</th>
                    <th>Сумма</th>
                    <th>Доход</th>
                    <th>Дата формирования</th>
                    <th>Причина</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for charge in charges %}
                <tr>
                    <td>
                        {{ charge.id }}
                    </td>
                    <td>
                        {{ charge.order }}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_text_form.html' with action='hostels:manage_edit_charge' type='text' id=charge.id name='value' value=charge.value %}
                    </td>
                    <td>

                        <form
                            role="form"
                            class="form-inline"
                            id="id{{ charge.id }}_is_income_form"
                            method="post"
                            action="{% url 'hostels:manage_edit_charge' id=charge.id %}?back={{ request.get_full_path }}"
                        >
                            {% csrf_token %}
                            <input type="hidden" name="back" value="{{ request.get_full_path }}">
                            <input type="hidden" id="id{{ charge.id }}_is_income_hidden" name="is_income" value="">
                            <div class="form-group">
                                <input
                                    type="checkbox"
                                    id="id{{ charge.id }}_is_income_input"
                                    name="is_income_chkbx"
                                    {% if charge.is_income %}checked{% endif %}
                                >
                            </div>
                        </form>
                        <script type="text/javascript">
                            $(document).ready(function() {
                                $("#id{{ charge.id }}_is_income_input").change(function() {
                                    if ($("#id{{ charge.id }}_is_income_input").prop("checked")) {
                                        $("#id{{ charge.id }}_is_income_hidden").val("1");
                                    } else {
                                        $("#id{{ charge.id }}_is_income_hidden").val("0");
                                    }
                                    $("#id{{ charge.id }}_is_income_form").submit();
                                });
                            });
                        </script>

                    </td>
                    <td>
                        {% include 'hostels/manage_edit_date_form.html' with action='hostels:manage_edit_charge' type='text' id=charge.id name='date' value=charge.date date_format='Y-m-d H:i:s' %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_select_form.html' with action='hostels:manage_edit_charge' id=charge.id name='status' value=charge.reason options=options.reasons selected=charge.reason %}
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog"></span>
                            <span class="caret"></span></button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#" onclick="console.log($('#createObject').find('[name=\'csrfmiddlewaretoken\']').val()); $.ajax({url: '{% url 'hostels:manage_edit_charge' id=charge.id %}', type: 'DELETE', csrfmiddlewaretoken: $('#createObject').find('[name=\'csrfmiddlewaretoken\']').val()}).done(function(){ location.reload(); });"><span class="glyphicon glyphicon-remove"></span> Удалить</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <div id="createObject" class="modal fade" role="dialog">
        <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Новый платёж</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="order_id" value="{{ request.GET.order_id }}">
                    <div class="form-group">
                        <label for="id_bed">Заказ:</label>
                        <select class="form-control" id="id_order" name="order">
                            {% for option_val, option_text in options.orders %}
                                <option value="{{ option_val.id }}" {% if option_val.id|add:'0' == request.GET.order_id|add:'0' %}selected{% endif %}>{{ option_text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_value">Сумма:</label>
                        <input type="text" class="form-control" id="id_value" name="value">
                    </div>
                    <div class="form-group">
                        <label for="id_is_income"><input type="checkbox" id="id_is_income" name="is_income" value="1"> Доход</label>
                    </div>
                    <div class="form-group">
                        <label for="id_date">Дата формирования:</label>
                        <input type="text" class="form-control" id="id_date" name="date">
                    </div>
                    <div class="form-group">
                        <label for="id_reason">Причина:</label>
                        <select class="form-control" id="id_reason" name="reason">
                            {% for option_val, option_text in options.reasons %}
                                <option value="{{ option_val.id }}">{{ option_text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-ok"></span>
                        Создать
                    </button>
                </form>
            </div>
        </div>

      </div>
    </div>

{% endblock %}

hostels/templates/hostels/manage_orders.html
{% extends 'hostels/base.html' %}

{% block title %}Заказы{% endblock %}

{% block content %}

    {% if error %}
        {% include "hostels/alert_template.html" with type="danger" message=error %}
    {% endif %}

    {% if request.GET %}
        <button type="button" class="btn btn-default" onclick="window.location = '{{ request.GET.back }}';"><span class="glyphicon glyphicon-arrow-left"></span> Назад</button>
    {% endif %}

    <button type="button" class="btn btn-default pull-right" data-toggle="modal" data-target="#createObject"><span class="glyphicon glyphicon-plus"></span> Добавить</button>

    <br><br>
    {% if orders %}
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Статус</th>
                    <th>Кровать</th>
                    <th>Дата въезда</th>
                    <th>Дата отъезда</th>
                    <th>Сумма</th>
                    <th>ФИО клиента</th>
                    <th>Паспортные данные клиента</th>
                    <th>Телефоны клиента</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>
                        {{ order.id }}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_select_form.html' with action='hostels:manage_edit_order' id=order.id name='status' value=order.status options=options.statuses selected=order.status %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_select_form.html' with action='hostels:manage_edit_order' id=order.id name='bed_id' value=order.bed.id options=options.beds selected=order.bed.id %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_date_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='start_date' value=order.start_date %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_date_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='end_date' value=order.end_date %}
                    <td>
                        {% include 'hostels/manage_edit_text_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='value' value=order.value %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_text_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='guest_full_name' value=order.guest_full_name %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_text_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='guest_identification' value=order.guest_identification %}
                    </td>
                    <td>
                        {% include 'hostels/manage_edit_text_form.html' with action='hostels:manage_edit_order' type='text' id=order.id name='guest_phone_number' value=order.guest_phone_number %}
                    </td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-cog"></span>
                            <span class="caret"></span></button>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="#" onclick="console.log($('#createObject').find('[name=\'csrfmiddlewaretoken\']').val()); $.ajax({url: '{% url 'hostels:manage_edit_order' id=order.id %}', type: 'DELETE', csrfmiddlewaretoken: $('#createObject').find('[name=\'csrfmiddlewaretoken\']').val()}).done(function(){ location.reload(); });"><span class="glyphicon glyphicon-remove"></span> Удалить</a></li>
                                <li class="dropdown-header">Связанные объекты</li>
                                <li><a href="{% url 'hostels:manage_charges' %}?order_id={{ order.id }}&back={{ request.get_full_path }}"><span class="glyphicon glyphicon-rub"></span> Платежи</a></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <div id="createObject" class="modal fade" role="dialog">
        <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Новый заказ</h4>
            </div>
            <div class="modal-body">
                <form role="form" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="hostel_id" value="{{ request.GET.hostel_id }}">
                    <input type="hidden" name="bed_id" value="{{ request.GET.hostel_id }}">
                    <div class="form-group">
                        <label for="id_bed">Кровать:</label>
                        <select class="form-control" id="id_bed" name="bed">
                            {% for option_val, option_text in options.beds %}
                                <option value="{{ option_val.id }}" {% if option_val.id|add:'0' == request.GET.bed_id|add:'0' %}selected{% endif %}>{{ option_text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_status">Статус:</label>
                        <select class="form-control" id="id_status" name="status">
                            {% for option_val, option_text in options.statuses %}
                                <option value="{{ option_val.id }}">{{ option_text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="id_start_date">Дата въезда:</label>
                        <input type="text" class="form-control" id="id_start_date" name="start_date">
                    </div>
                    <div class="form-group">
                        <label for="id_end_date">Дата отъезда:</label>
                        <input type="text" class="form-control" id="id_end_date" name="end_date">
                    </div>
                    <div class="form-group">
                        <label for="id_value">Сумма:</label>
                        <input type="text" class="form-control" id="id_value" name="value">
                    </div>
                    <div class="form-group">
                        <label for="id_guest_full_name">ФИО клиента:</label>
                        <input type="text" class="form-control" id="id_guest_full_name" name="guest_full_name">
                    </div>
                    <div class="form-group">
                        <label for="id_guest_identification">Паспортные данные клиента:</label>
                        <input type="text" class="form-control" id="id_guest_identification" name="guest_identification">
                    </div>
                    <div class="form-group">
                        <label for="id_guest_phone_number">Телефоны клиента:</label>
                        <input type="text" class="form-control" id="id_guest_phone_number" name="guest_phone_number">
                    </div>
                    <button type="submit" class="btn btn-default">
                        <span class="glyphicon glyphicon-ok"></span>
                        Создать
                    </button>
                </form>
            </div>
        </div>

      </div>
    </div>

{% endblock %}